const fs = require('fs')
const path = require('path')
const db = require('../src/db')
const schema = fs.readFileSync(path.join(__dirname,'..','migrations','schema.sql'),'utf8')
db.exec(schema)
// Seeds básicos
const insertRole = db.prepare('INSERT OR IGNORE INTO roles(name) VALUES (?)')
insertRole.run('admin')
insertRole.run('gerente')
insertRole.run('recepcao')
insertRole.run('medico')
insertRole.run('tecnico')
insertRole.run('paciente')
const insertPatient = db.prepare('INSERT OR IGNORE INTO patients(name, cpf, cns, phone) VALUES (?,?,?,?)')
insertPatient.run('João Silva','11122233344','12345678901','+55 11 99999-0000')
console.log('DB initialized and seeds applied')
